from enum import Enum


class Context(Enum):
    VIDEO_FILTER = "VIDEO_FILTER"
    VIDEO_CODEC_OPTION = "VIDEO_CODEC_OPTION"
    VIDEO_SPECIAL_CODEC_OPTIONS = "VIDEO_SPECIAL_CODEC_OPTIONS"

    AUDIO_CODEC ="AUDIO_CODEC"
    AUDIO_CODEC_OPTION = "AUDIO_CODEC_OPTION"
    AUDIO_FILTER = "AUDIO_FILTER"

    SPECIAL = "SPECIAL"

class Type(Enum):
    DIRECT ="DIRECT"
    CHOICE = "CHOICE"
    HANDLED = "HANDLED"